language: node_js
sudo: required
node_js: stable
cache:
  directories:
    - node_modules
script:
  - yarn run test
branches:
  except:
    - gh-pages
before_deploy:
  - yarn run build
deploy:
  provider: pages
  skip_cleanup: false
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: build/
  target_branch: gh-pages
  on:
    branch: master
dist: trusty