language: node_js
sudo: required
node_js: stable
cache:
  directories:
  - node_modules
before_install:
- npm install -g babel-cli
script:
- yarn run lint
- yarn run test
- ./node_modules/coveralls/bin/coveralls.js <./coverage/lcov.info
branches:
  except:
  - gh-pages
before_deploy:
- yarn run demo
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: demo/
  target_branch: gh-pages
  on:
    branch: master
dist: trusty