language: node_js
sudo: required
node_js: stable
cache:
  directories:
  - node_modules
before_install:
script:
- yarn run test
branches:
  except:
  - gh-pages
before_deploy:
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: demo/
  target_branch: gh-pages
  on:
    branch: master
dist: trusty